<main>
    <?php if (!empty($_SESSION) && $_SESSION['admin'] === 'yes'){ ?>
    <a class="button button-primary" href='#delete'>Suprimer</a>
    <a class="button button-primary" href="index.php?route=update&amp;id=<?= $getArticle->getId(); ?>">Modifier</a>
    <section>
        <article id="delete" class="modal">
            <section class="modal-window">
                <p>Etes vous sur de voulair suprimer cette article</p>
                <section class="choice">
                    <a class="button button-secondary" class="close" href="#">Annuler</a>
                    <a class="button button-primary" href="index.php?route=delete&amp;id=<?= $getArticle->getId(); ?>">Suprimer</a>
                </section>
            </section>
        </article>
    </section>
    <?php } ?>
    <section class="article">
        <article>
                <img src="/Blog_felin/<?=$getArticle->getMedia()->getUrl()?>"></img>
                <section>
                    <?= $getArticle->getContent(); ?> 
                </section>
        </article>
    </section>
    <section class="messages">
    <h1>Messages</h1>
        <?php foreach($getMessage as $message){ ?>    
        <article class="message">
            <section>
                <h3><?= $message->getUsername(); ?></h3>
                <p>Envoyé le <span><?= $message->getDate(); ?></span></p>
            </section>
            <p><?= $message->getContent(); ?></p>
        </article>
        <?php } ?>
    </section>
        
<?php if (!empty($_SESSION)){ ?>
<form name="form_message" action="index.php?route=article&amp;id=<?= $getArticle->getId(); ?>" method="post">
    <input type="hidden" name="name" value="<?= $_SESSION['name']; ?>"/>
    <input type="hidden" name="id" value="<?= $_GET['id']; ?>"/>
    <textarea type="textarea" cols="50" rows="10"  name="message" maxLength="255" id="textarea"></textarea>
    <input type="submit" name="submit" value="Poster" id="submit"/>
</form>
<?php }else{ ?>
<h5 class="connect-message">Pour poster un message veuillez vous <a href="index.php?route=signIn"><span class="line">connectez</span></a></h5>
<?php } ?>
</main>