<main>
    <h1>Formulaire de contact</h1>
    <form name="form_contact" action="index.php?route=contactUs" method="post">
        <label> Nous contacter</label>
        <input type="text" name="name" class="long"/>
        <label>Votre adresse e-mail</label>
        <input type="email" name="email" class="long"/>
        <label> Message </label>
        <textarea name="message" class="long field-textarea"></textarea>
        <input type="submit" name="submit" value="Envoyer">      
    </form>
</main>