    <footer>
        <article class="footer-category">
            <!--Eb construction-->
            <!--<section>-->
            <!--    <h1>Aide et contact</h1>-->
            <!--    <a href="index.php?route=contactUs">Nous contacter</a>-->
            <!--</section>-->
            <section>
                <h1>Informations</h1>
                <a href="">Mes chats</a>
            </section>
            <section class="reseaux">
                <h1>Nos reseaux</h1>
                <article>
                    <a href="https://fr-fr.facebook.com/"><i class="fa-brands fa-3x fa-facebook-square"></i></a>
                    <a href="https://www.instagram.com/"><i class="fa-brands fa-3x fa-instagram-square"></i></a>
                    <a href="https://twitter.com/"><i class="fa-brands fa-3x fa-twitter-square"></i></a>
                </article>
            </section>
        </article>
        <article>
            <p class="copyright">Copyright jdhfskjdhfksjhfksdjhfksdjhfksdjhfskdjhfks</p>
        </article>
    </footer>
<body>