<footer>
    <article class="footer-category">
        
        
        <!--En construction-->
        <!--<section>-->
        <!--    <h1>Aide et contact</h1>-->
        <!--    <a href="index.php?route=contactUs">Nous contacter</a>-->
        <!--</section>-->
        
        
        
        <section>
            <h2>Informations</h2>
            <a href="index.php?route=my-cats">Mes chats</a>
        </section>
        <section class="reseaux">
            <h2>Nos reseaux</h2>
            <article>
                <a href="https://fr-fr.facebook.com/"><i class="fa-brands fa-2x fa-facebook-square"></i></a>
                <a href="https://www.instagram.com/"><i class="fa-brands fa-2x fa-instagram-square"></i></a>
                <a href="https://twitter.com/"><i class="fa-brands fa-2x fa-twitter-square"></i></a>
            </article>
        </section>
    </article>
    <article>
        <p class="copyright">Copyright jdhfskjdhfksjhfksdjhfksdjhfksdjhfskdjhfks</p>
    </article>
</footer>