<footer>
    <section class="flex sb">
        <div>
            <h1>Aide et contact</h1>
            <a href="index.php?route=contactUs">Nous contacter</a>
        </div>
        <div>
            <h1>Informations</h1>
            <a href="">Politique de confidentialité</a>
        </div>
        <div class="reseaux">
            <h1>Nos reseaux</h1>
            <div>
                <a href="https://fr-fr.facebook.com/"><i class="fa-brands fa-2x fa-facebook-square"></i></a>
                <a href="https://www.instagram.com/"><i class="fa-brands fa-2x fa-instagram-square"></i></a>
                <a href="https://twitter.com/"><i class="fa-brands fa-2x fa-twitter-square"></i></a>
            </div>
        </div>
    </section>
    <div>
        <p>Copyright jdhfskjdhfksjhfksdjhfksdjhfksdjhfskdjhfks</p>
    </div>
</footer>