<?php session_start();?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog felin</title>
    <link rel="icon" href="./asset/images/logo.png" type="image/x-icon" />
    <link rel="stylesheet" href="/asset/css/style.css">
    <meta name="viewport" content="width=device-width"/>
    <script src="https://kit.fontawesome.com/dc3e73b9f2.js" crossorigin="anonymous"></script>
</head>

<body>
    <header class="homescreen">
        <nav>
            <a href="index.php?route=homescreen"><img class="logo" src="./asset/images/logo.png" alt="logo"></a>
            <label for="checkbox" id="label"></label>
            <input type="checkbox"  id="checkbox"/>
            <ul class="nav-links">
                <li><a href="index.php?route=homescreen">Accueil</a></li>
                <li><a href="index.php?route=species">Liste des espèces</a></li>
                <li><a href="index.php?route=news">Actualités</a></li>
                
                <?php if (isset($_SESSION['isLogin']) && $_SESSION['isLogin'] === true){ ?>
                <li><p><?php if(isset($_SESSION['name'])){echo $_SESSION['name'];} ?></p></li>
                <li><a href="index.php?route=disconnect"><p>Deconnexion</p></a></li>
                <?php }else{ ?>
                <li><a href="index.php?route=signIn"><p>Se connecter</p></a></li>
                
                <?php } ?>
                
                <?php if (isset($_SESSION['admin']) && $_SESSION['admin'] === 'yes'){ ?>
                <li><a href="index.php?route=newArticle">Nouvel article</a></li>
                <?php } ?>
            </ul>
        </nav>
    </header>