<?php session_start();?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog felin</title>
    <link rel="icon" href="/Blog_felin/asset/images/logo.png" type="image/x-icon" />
    <link rel="stylesheet" href="/Blog_felin/asset/css/style.css">
    <meta name="viewport" content="width=device-width"/>
    <script src="https://kit.fontawesome.com/dc3e73b9f2.js" crossorigin="anonymous"></script>
    
</head>
<header class="homescreen">
    <nav>
        <a href="index.php?route=homescreen"><img class="logo" src="./asset/images/logo.png" alt=""></a>
        <ul class="nav-links">
            <li><a href="index.php?route=homescreen">Accueil</a></li>
            <li><a href="index.php?route=species">Liste des espèce</a></li>
            <li><a href="index.php?route=news">Actualités</a></li>
            
            <?php if (isset($_SESSION['isLogin']) && $_SESSION['isLogin'] === true){ ?>
            <li><p><?php if(isset($_SESSION['name'])){echo $_SESSION['name'];} ?></p></li>
            <li><a href="index.php?route=disconnect"><p>Deconexion</p></a></li>
            <?php }else{ ?>
            <li><a href="index.php?route=signIn"><p>Se connecter</p></a></li>
            
            <?php } ?>
            
            <?php if (isset($_SESSION['admin']) && $_SESSION['admin'] === 'yes'){ ?>
            <li><a href="index.php?route=newArticle">Nouvelle article</a></li>
            <?php } ?>
        </ul>
        <img class="menu-hamburger" src="/Blog_felin/asset/images/hamburger-menu-icon-png-white-10.jpg"></img>
    </nav>
</header>