<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog felin</title>
    <link rel="icon" href="./asset/images/logo.png" type="image/x-icon" />
    <link rel="stylesheet" href="./asset/css/accueil/header-template.css">
    <link rel="stylesheet" href="./asset/css/base.css">
    <link rel="stylesheet" href="./asset/css/accueil/body.css">
    <link rel="stylesheet" href="./asset/css/accueil/footer.css">
    <script src="https://kit.fontawesome.com/dc3e73b9f2.js" crossorigin="anonymous"></script>
    
</head>

<?php session_start();?>

<header>
    <nav class="navbar">
        <div class="flex ">
            <a href="index.php?route=homescreen"><img src="./asset/images/logo.png" alt=""></a>
            <a href="index.php?route=homescreen">Accueil</a>
            <a href="index.php?route=species">Liste des espèce</a>
            <a href="index.php?route=news">Actualités</a>
            
            <?php if (!$_SESSION){ ?>
            <a href="index.php?route=signIn"><p>Se connecter</p></a>
            <?php }else{ ?>
            <p><?= $_SESSION['name']; ?></p>
            <a href="index.php?route=disconnect"><p>deconexion</p></a>
            <?php } ?>
            
            <?php if (!empty($_SESSION) && $_SESSION['admin'] === 'yes'){ ?>
            <a href="index.php?route=newArticle"><p>Nouvelle article</p></a>
            <?php } ?>
        </div>
    </nav>
</header>