<main>
<?php foreach ($getArticle as $article){?>  
        <article class="articles border">
            <img src="<?=$article->getMedia()->getUrl();?> " alt="<?=$article->getAlt();?>">
            <section class="card">
                <section class="content">
                    <?= $article->getContent(); ?> 
                </section>
                <a href="index.php?route=article&amp;id=<?= intval($article->getId()); ?>"><span class="line">Lire la suite</span></a>
            </section>
        </article>
        <?php } ?>
        <script  src="./asset/javascript/clear_session_storage.js"></script>
</main>