<div id="container">
      <div id="parallax"></div>
</div>

<main class="flex sb">
    <section class="article">
        <article>
            <div>
                <img src="https://cdn.futura-sciences.com/buildsv6/images/wide1920/e/f/a/efa57a13ca_78508_canonique-751.jpg"></img>
            </div>
            <h1>Ce chat est OKLM c'est ouf OMG!!!!!!</h1>
        </article>
                <article>
            <div>
                <img src="https://cdn.futura-sciences.com/buildsv6/images/wide1920/e/f/a/efa57a13ca_78508_canonique-751.jpg"></img>
            </div>
            <h1>Ce chat est OKLM c'est ouf OMG!!!!!!</h1>
        </article>
                <article>
            <div>
                <img src="https://cdn.futura-sciences.com/buildsv6/images/wide1920/e/f/a/efa57a13ca_78508_canonique-751.jpg"></img>
            </div>
            <h1>Ce chat est OKLM c'est ouf OMG!!!!!!</h1>
        </article>
    </section>
    <section class="sugestion fix">
        <div class="card">
            <h1>Les derniers articles</h1>
            <div class="flex sb">
                <div class="imgSugestion">
                    <img src="https://cdn.futura-sciences.com/buildsv6/images/wide1920/e/f/a/efa57a13ca_78508_canonique-751.jpg"></img>
                </div>
                 <h2>Ce chat est OKLM c'est ouf OMG!!!!!!</h2>
            </div>
            <div class="flex sb">
                <div class="imgSugestion">
                    <img src="https://cdn.futura-sciences.com/buildsv6/images/wide1920/e/f/a/efa57a13ca_78508_canonique-751.jpg"></img>
                </div>
                 <h2>Ce chat est OKLM c'est ouf OMG!!!!!!</h2>
            </div>
            <div class="flex sb">
                <div class="imgSugestion">
                    <img src="https://cdn.futura-sciences.com/buildsv6/images/wide1920/e/f/a/efa57a13ca_78508_canonique-751.jpg"></img>
                </div>
                 <h2>Ce chat est OKLM c'est ouf OMG!!!!!!</h2>
            </div>
        </div>
        <div class="card">
            <h1>Les derniers articles</h1>
            <div class="flex sb">
                <div class="imgSugestion">
                    <img src="https://cdn.futura-sciences.com/buildsv6/images/wide1920/e/f/a/efa57a13ca_78508_canonique-751.jpg"></img>
                </div>
                 <h2>Ce chat est OKLM c'est ouf OMG!!!!!!</h2>
            </div>
            <div class="flex sb">
                <div class="imgSugestion">
                    <img src="https://cdn.futura-sciences.com/buildsv6/images/wide1920/e/f/a/efa57a13ca_78508_canonique-751.jpg"></img>
                </div>
                 <h2>Ce chat est OKLM c'est ouf OMG!!!!!!</h2>
            </div>
            <div class="flex sb">
                <div class="imgSugestion">
                    <img src="https://cdn.futura-sciences.com/buildsv6/images/wide1920/e/f/a/efa57a13ca_78508_canonique-751.jpg"></img>
                </div>
                 <h2>Ce chat est OKLM c'est ouf OMG!!!!!!</h2>
            </div>
        </div>
    </section>
</main>