<?php 
if($page === "homescreen"){
    require"header_homescreen.phtml";
}else{
    require"header.phtml";
}?>
<?php require "./templates/".$page.".phtml"; ?>
<?php require"footer.phtml" ?>
<script type="text/javascript" src="/Blog_felin/asset/javascript/accueil/header.js"></script>
<script type="text/javascript" src="/Blog_felin/asset/javascript/accueil/menu_hamburger.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/35.0.1/classic/ckeditor.js"></script>

