<main>
    <h1>Inscription</h1>
    <form name="form_registration" action="index.php?route=registration" method="post">
        <label> Nom d'utilisateur</label>
        <input type="text" name="username" class="long"/>
        <label>Mots de passe</label>
        <input type="password" name="password" class="long"/>
        <input type="submit" name="submit" value="Inscription"> 
    </form>
</main>