<main>
    <h1>Connexion</h1>
    <form name="form_signIn" action="index.php?route=signIn" method="post">
        <label> Nom d'utilisateur</label>
        <input type="text" name="username" class="long"/>
        <label>Mots de passe</label>
        <input type="password" name="password" class="long"/>
        <input type="submit" name="submit" value="Se connecter">       
    </form>
    <p>Si vous n'ete pas inscrit <a href="index.php?route=registration">Inscriver-vous</a></p>
</main> 