<main class="sb">
<?php
    foreach ($getArticle as $article){ 
        if($article->getCategory() === 'espece'){ ?>
    <section class="article">
        <article>
            <div>
                <img src="<?=$article->getMedia()->getUrl();?>"></img>
            </div>
            <h1><?= $article->getTitle(); ?></h1>
            <p><?= $article->getDescription(); ?></p>
            <a href="index.php?route=article&amp;id=<?= $article->getId(); ?>">lire la suite</a>
        </article>
    </section>
<?php   
        } 
    }
?>
</main>