<main>
    <h1>Modifier Article</h1>
    <form class="editor" name="form_update" action="index.php?route=update&amp;id=<?= $_GET['id'];?>" method="post" enctype="multipart/form-data">
        <input type="hidden" name="id" value="<?= $_GET['id'];?>"/>
        <label> Quelle categorie</label>
        <select name="category" id="category">
            <option>Actualité</option>
            <option>Espèce</option>
            <option selected="selected"><?= $getArticle->getCategory();?></option>
        </select>
        <label> contenue </label>
        <textarea name="content" id="content" maxlength="10000"></textarea>
        <label>Selectionner l'image a upload</label>
        <section>
            <input type="file" name="image" id="fileToUpload">
            <input name="descriptionImg" id="descriptionImg" maxlength="255" placeholder="Décrire l'image" value=<?= $getArticle->getAlt();?>>
        </section>    
        <?php
            if(isset($_SESSION['error'])){
                echo $_SESSION['error'];
                unset($_SESSION['error']);
            }?>
        <input type="submit" name="submit" value="Modifier" id="submit">
    </form>
    <script type="text/javascript" src="./asset/javascript/form_new_article.js"></script>
</main>